//@ts-ignore
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import MobileWarning from "./components/MobileWarning";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Loopify",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <MobileWarning />
        {children}
      </body>
    </html>
  );
}
